# timelapse_infer.py
import argparse
from pathlib import Path

# ### MODIFIED ###: Import ImageDraw and ImageFont for drawing text
from PIL import Image, ImageDraw, ImageFont

from sam2_inference import (
    generate_point_grid,
    load_model,
    find_mask_path,
    run_inference,
)
import tqdm


def main():
    ap = argparse.ArgumentParser(
        description="Run inference across checkpoints and create a GIF"
    )
    ap.add_argument("--image", required=True, help="Path to a raw dataset image")
    ap.add_argument(
        "--ckpt_dir", required=True, help="Directory containing checkpoint .pt files"
    )
    ap.add_argument(
        "--grid_points", type=int, default=32, help="Number of grid points per side"
    )
    ap.add_argument(
        "--output", default="timelapse.gif", help="Filename for the output GIF"
    )
    ap.add_argument(
        "--duration", type=int, default=500, help="Frame duration in milliseconds"
    )
    args = ap.parse_args()

    img_path = Path(args.image)
    mask_path = find_mask_path(img_path)
    grid = generate_point_grid(args.grid_points)

    ckpt_dir = Path(args.ckpt_dir)
    ckpts = sorted(ckpt_dir.glob("*.pt"), key=lambda x: int(str(x).split("_ep")[-1].split(".pt")[0]))
    if not ckpts:
        raise ValueError(f"No checkpoints found in {ckpt_dir}")

    frames = []
    tmp_dir = ckpt_dir / "timelapse_frames"
    tmp_dir.mkdir(exist_ok=True)

    # ### MODIFIED ###: Load a font for the overlay.
    # Tries to load a common system font, otherwise falls back to Pillow's default.
    # You may need to change "arial.ttf" to a font path on your system,
    # e.g., "C:/Windows/Fonts/arial.ttf" or "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
    try:
        font = ImageFont.truetype("arial.ttf", 24)
    except IOError:
        print("Arial font not found. Using default font. Text will be smaller.")
        font = ImageFont.load_default()

    # ### MODIFIED ###: Use enumerate to get a frame index (i)
    for i, ckpt in enumerate(tqdm.tqdm(ckpts)):
        model = load_model(str(ckpt))
        out_path = tmp_dir / f"{ckpt.stem}.png"
        run_inference(model, img_path, mask_path, grid, out_path)
        
        # ### MODIFIED ###: Open the generated frame, add overlay, then append
        # Open the image generated by run_inference
        frame_image = Image.open(out_path).convert("RGBA")

        # Create a drawing context
        draw = ImageDraw.Draw(frame_image)
        
        # Extract the checkpoint number from the filename (same logic as sorting)
        ckpt_epoch = str(ckpt).split("_ep")[-1].split(".pt")[0]
        text = f"Frame: {i + 1} / Ckpt Epoch: {ckpt_epoch}"
        
        # Define text position and color
        text_position = (15, 15)
        text_color = (255, 255, 255) # White

        # --- Add a semi-transparent background for better readability ---
        # Get the bounding box of the text
        try:
            # For newer Pillow versions
            bbox = draw.textbbox(text_position, text, font=font)
        except AttributeError:
            # For older Pillow versions
            text_width, text_height = draw.textsize(text, font=font)
            bbox = (text_position[0], text_position[1], text_position[0] + text_width, text_position[1] + text_height)

        # Create a padded bounding box for the background rectangle
        bg_bbox = (bbox[0] - 10, bbox[1] - 5, bbox[2] + 10, bbox[3] + 5)
        
        # Draw the rectangle background and the text
        draw.rectangle(bg_bbox, fill=(0, 0, 0, 128)) # Black with 50% opacity
        draw.text(text_position, text, font=font, fill=text_color)
        
        # Append the modified frame to the list. Convert back to RGB for GIF compatibility.
        frames.append(frame_image.convert("RGB"))


    if frames:
        frames[0].save(
            args.output,
            save_all=True,
            append_images=frames[1:],
            duration=args.duration,
            loop=0,
        )
        print(f"Saved timelapse to {args.output}")


if __name__ == "__main__":
    main()
